### ISSUE TITLE
Explicitly depend on minimap package?

### ISSUE THREAD

**Issue by simonrepp** [ansballard/minimap-autohider#13]
I set up fresh atom installs every now and then, `minimap-autohider` is one of around 5 packages that is always part of the installation routine. (:heart: it, thanks!) I've been using my current atom setup for a few weeks now when I finally realized something was odd - there was no minimap. So I spent a good 15 minutes wondering when it disappeared and why, disabling packages, altering settings, after all I had installed `minimap-autohider`, hadn't I? ... well then it dawned on me that `minimap` itself is not a default thing, I didn't install it back a few weeks.

Now this is of course a sign of brain decay on my part :rofl: (I *had* known that `minimap` is not a default install for years), but at the same time it shows this *can* happen and go unnoticed, that's why I'd like to bring it up ... there is a really simple metapackage out there for ensuring atom package dependencies, which I've been happily using in a production scenario somewhere:

https://www.npmjs.com/package/atom-package-deps

If you are inclined to integrate that, awesome, I'll gladly submit a PR too if you'd prefer that, and all the same I also totally understand if you consider this not necessary and would like to keep minimap-autohider as small and bare as possible. :)

Thanks!
Simon

**Comment by ansballard** [comment]
oh interesting, I hadn't thought through that someone may install this but not minimap, or that there's already a package to handle that kind of dependency in atom. I'll definitely see if i can get this integrated, looks like that package is maintained by steelbrain so I'm happy to add it.

Thanks for the issue!

**Comment by simonrepp** [comment]
That's great, thanks! :+1:

**Comment by ansballard** [comment]
https://github.com/ansballard/minimap-autohider/commit/79e7c079d7af881bdb6a5d842361d7ad50c4ee3c should be resolved as of 1.6.0

**Comment by simonrepp** [comment]
Awesome, already updated everywhere :) thanks!
