### ISSUE TITLE
Window shifts left instead of hiding the minimap

### ISSUE THREAD

**Issue by paul-arthurthiery** [ansballard/minimap-autohider#15]
Description
With Atom 1.39, the minimap authohide now causes the whole window to shift left (see given screenshots)

Steps to Reproduce

1. Open a project directory
2. Open a file which will trigger the minimap display
3. Click on another file in the tree view

Expected behavior:

Minimap should be completely hidden, and no window shift should appear

Actual behavior:

Window is now completely warped to the left and minimap is somewhat transparent but not hidden

Reproduces how often:

Always

Versions
Atom : 1.39.1
Electron: 3.1.10
Chrome : 66.0.3359.181
Node : v10.2.0

MacOS Mojave 10.14.5

![Screen Shot 2019-07-31 at 10 40 02 AM](https://user-images.githubusercontent.com/17085620/62223464-f50e8280-b382-11e9-91b2-000cfd205722.jpg)
![Screen Shot 2019-07-31 at 10 39 54 AM](https://user-images.githubusercontent.com/17085620/62223465-f50e8280-b382-11e9-99c5-6b9e13c9e91d.jpg)

**Comment by ansballard** [comment]
Just downloaded 1.39.1 and tested (I'm also on osx), and I'm not able to reproduce the issue. It's possible it was something introduced in 1.39.0 and patched, so I would try again. If it's still an issue I'll need to see what setting you're using for minimap and minimap-autohider, in case there's some settings in conflict that I haven't run into.

**Comment by ansballard** [comment]
Haven't heard back and couldn't reproduce the issue so I'm going to go ahead and close this, if it's still broken for you just let me know!

**Comment by mike-source** [comment]
I can see this issue happening in Atom 1.41.0, very annoying and means I have to disable the plugin to even use Atom.

It had been happening sporadically and hard to recreate consistently until this morning where it happens every time I open a file large enough to use minimap.

Steps to reproduce are exactly as in the original issue.

Atom 1.41.0
macOS High Sierra: 10.13.6
Minimap 4.29.9
Minimap Autohide 0.10.1

Settings for minimap are as follows:

![Screen Shot 2019-10-30 at 11 15 31](https://user-images.githubusercontent.com/6898265/67853605-d5fcc980-fb06-11e9-9d2c-ea3425d235ca.png)
![Screen Shot 2019-10-30 at 11 15 56](https://user-images.githubusercontent.com/6898265/67853627-dac17d80-fb06-11e9-9f56-3133b842fa4b.png)
