### ISSUE TITLE
Window shifts left instead of hiding the minimap

### ISSUE THREAD

**Issue by mike-source** [ansballard/minimap-autohider#16]
I can see this issue happening in Atom 1.41.0, very annoying and means I have to disable the plugin to even use Atom.

It had been happening sporadically and hard to recreate consistently until this morning where it happens every time I open a file large enough to use minimap.

Steps to reproduce are exactly as in the original issue.

Atom 1.41.0
macOS High Sierra: 10.13.6
Minimap 4.29.9
Minimap Autohide 0.10.1

Settings for minimap are as follows:

![Screen Shot 2019-10-30 at 11 15 31](https://user-images.githubusercontent.com/6898265/67853605-d5fcc980-fb06-11e9-9d2c-ea3425d235ca.png)
![Screen Shot 2019-10-30 at 11 15 56](https://user-images.githubusercontent.com/6898265/67853627-dac17d80-fb06-11e9-9f56-3133b842fa4b.png)

_Originally posted by @mike-source in https://github.com/ansballard/minimap-autohider/issues/15#issuecomment-547852846_

**Comment by jspv** [comment]
I'm seeing the exact same behavior.

**Comment by ansballard** [comment]
@jspv would you mind listing your atom/os specs as well?

**Comment by ansballard** [comment]
Oh, this is a different package, sorry for the confusion. This repo is a fork of https://github.com/jayk/minimap-autohide, published as `minimap-autohider` (note the **r** at the end). Going to close this, feel free to re-open if installing the correct library still gives you issues. Ty!
