### ISSUE TITLE
Newest version has broken

### ISSUE THREAD

**Issue by iAmMichaelConnor** [ansballard/minimap-autohider#19]
I've had this package installed for years. Updated to the newest version yesterday, and it's not working, in the sense that it _permanently hides_ the minimap.
If I scroll, the minimap doesn't appear. 
If I disable this package, then the minimap appears (permanently).

v 1.7.0

**Comment by johnjcamilleri** [comment]
Same here, minimap-autohider 1.7.0 and minimap 4.39.5.

**Comment by iAmMichaelConnor** [comment]
I downgraded to v1.6.0 (`apm install minimap-autohider@1.6.0`) but it still doesn't work.

So perhaps the problem is caused by the latest `minimap` package (because I also updated that at the same time I updated all the other minimap-related packages).

**Comment by depeele** [comment]
Seems to be an issue introduced with minimap 4.39.1.

Downgrading to minimap 4.39.0 or 4.38.3 (`apm install minimap@4.39.0`) fixed this issue for me...

**Comment by aminya** [comment]
Please do not downgrade Minimap. It includes important fixes. I will try to fix auto-hide as soon as possible.

**Comment by UziTech** [comment]
This should be fixed in [minimap@4.39.7](https://github.com/atom-minimap/minimap/releases/tag/v4.39.7)

**Comment by iAmMichaelConnor** [comment]
@UziTech thanks very much for the prompt fix!
I've updated to minimap@4.39.7, re-enabled and re-checked the 'minimap-autohider' box in Minimap's settings, and it works :) 
I'll go ahead and close the issue!
