### ISSUE TITLE
DeprecationWarning: Calling an asynchronous function without callback is deprecated.

### ISSUE THREAD

**Issue by Ben3eeE** [ansballard/minimap-autohider#3]
We are in progress of [upgrading to Electron 1.6](https://github.com/atom/atom/pull/12696) and noticed a deprecation from your package. In particular we found the following deprecation when activating the package:

```
(node:21264) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
process.on @ internal/process/warning.js:21
emitOne @ events.js:96
emit @ events.js:188
process.nextTick @ internal/process/warning.js:47
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
```

It seems that your package is not specifying a callback when calling `fs.writeFile` (https://github.com/ansballard/minimap-autohider/blob/master/lib/minimap-autohider.js#L64).

Please, let me know if you have any questions or concerns and if I can help somehow. Thanks!

/cc: @as-cii

**Comment by ansballard** [comment]
Looks like that callback was flagged as required in node 7.0.0, so I'll add in some barebones error checking in the callback which should get rid of that deprecation warning. Thanks for the heads up!

**Comment by ansballard** [comment]
Pushed 1.4.0 last night, which adds a callback to writeFile and uses `atom.notifications` in case of errors. Let me know if that doesn't take care of the deprecation warnings!
