### ISSUE TITLE
[ENHANCEMENT] hover over area to unhide minimap

### ISSUE THREAD

**Issue by kinghat** [ansballard/minimap-autohider#4]
a solid feature would be to have the size of the minimap when not hidden be a hover area so when you moused over that area you could have it unhide itself. you could make it so this was the only unhide option or you could have both this and the scroll method to unhide the minimap. personally i would just use the hover method as i find it distracting sometimes when im just scrolling a bit or when im not even intending to scroll but my hands have a mind of their own. everything else stays the same with delays and such, its just a different way to unhide the minimap.

ty for the minimap extension!

![atom_2017-06-02_21-44-30](https://cloud.githubusercontent.com/assets/16073360/26749966/33abda92-47dd-11e7-8a46-461f7d848b96.png)

**Comment by kinghat** [comment]
awesome update! using the feature right now and it's slick. can you add a sub field to the hover option to allow us to set a custom hover area(like 50% or 75%) or is that not how it works? 

also, how do you feel about a 'replace as scrollbar' type option? some peoples theme might not show the scrollbars but for those that do, a replace as scrollbar would be an enhancement. im not sure if you would actually get rid of the scrollbar or change it to invisible. not sure how that works.

![atom_2017-06-04_11-18-43](https://cloud.githubusercontent.com/assets/16073360/26763382/a0619682-4917-11e7-95ae-35204c25e6c4.png)

**Comment by ansballard** [comment]
Glad it's working! Changing the amount it's hidden is no big deal, especially if it's locked to 25%, 50%, 75%, and 100%. Actually if I add 0%, I could just replace that option, so I'll probably do that. As for replacing the scrollbar, I guess just having an option to hide it would work.

**Comment by kinghat** [comment]
ya on the% thing I was just trying to say how big the area is for it to trigger the menu expansion. not sure if I was confused by your option description or not? thanks for being an awesome dev that cares about user input.

**Comment by ansballard** [comment]
No problem, I think I actually confused myself on that one. Just pushed out 1.5.1, which replaces the ShowOnHover boolean with a dropdown list of percentages. The default is 0, so the minimap is fully hidden when inactive by default. So if you wanted it 50% visible, you can set that option to 50. I also made sure I was actually toggling that option, since it was turned on no matter what lol. And thank you so much, I'm just glad people can get some use out of this library =)

**Comment by kinghat** [comment]
super sexy! thanks @ansballard!

**Comment by kinghat** [comment]
i did a hard edit on the theme i am using to make its scrollbars invisible and that seemed to work but its not permanent and it knocks out all scrollbars(like in the settings) so using a userstyle override might not be the way to go.

**Comment by ansballard** [comment]
Yea, I played with the scrollbars a bit but didn't have as much time as I thought last night, so that option might have to wait a bit. What's the css edit you made? I would've thought `atom-text-editor .vertical-scrollbar` wouldn't grab scrollbars on the settings page, but that's just a guess.

**Comment by kinghat** [comment]
i think something may be wrong with this. when trying to remove the scrollbars in just the editor windows for a better look to the minimap i noticed that the 'show on hover' option is not the same size in two equally sized panes side by side. you can see in the image below that i outlined the right panes region which is smaller and copied it over to the left panes region to compare, though it is hard to see. if you see the image at full size you can see it more clearly.

![atom_2017-06-16_09-17-20](https://user-images.githubusercontent.com/16073360/27235731-90384200-5287-11e7-95d0-7cb226434aeb.png)


btw:
`atom-text-editor .vertical-scrollbar` this didnt seem to work and i also tried this:
```
::-webkit-scrollbar {
    display: none;
}
```
which worked but got rid of scrollbars everywhere.

**Comment by kinghat** [comment]
this seems to have been fixed with the latest fix of https://github.com/ansballard/minimap-autohider/issues/6
![chrome_2017-06-16_11-22-54](https://user-images.githubusercontent.com/16073360/27235663-4345a88e-5287-11e7-8bcd-d4644ea48910.png)
