### ISSUE TITLE
TextEditor.editorElement is deprecated.

### ISSUE THREAD

**Issue by nibushibu** [ansballard/minimap-autohider#5]
`TextEditor.prototype.editorElement` has always been private, but now
it is gone. Reading the `editorElement` property still returns a
reference to the editor element but this field will be removed in a
later version of Atom, so we recommend using the `element` property instead.
```
TextEditor.editorElement (<embedded>:2383:20)
minimapsSubscription.minimap.observeMinimaps.minimap (/Users/nibushibu/.atom/packages/minimap-autohider/lib/minimap-autohider.js:40:13)
editorsMinimaps.forEach (/Users/nibushibu/.atom/packages/minimap/lib/main.js:377:51)
Map.forEach (native)
Main.observeMinimaps (/Users/nibushibu/.atom/packages/minimap/lib/main.js:377:28)
Object.activatePlugin (/Users/nibushibu/.atom/packages/minimap-autohider/lib/minimap-autohider.js:30:53)
```

**Comment by ansballard** [comment]
Thanks for the heads up! Just pushed an update, 1.5.2 that should resolve it.
