### ISSUE TITLE
Show minimap on mouseover

### ISSUE THREAD

**Issue by nonnymoose** [ansballard/minimap-autohider#8]
Could you do this? I really would like the minimap to appear at a moment's notice, rather than having to click on the code on the right. (Clicking on the scrollbar does not activate the minimap.)

Thanks!

**Comment by ansballard** [comment]
I think this should already be possible. By default the minimap is completely hidden, but there's a setting (Visible Percentage) that allows you to change that. So if you made it, say, 25%, you could mouse over to the scrollbar at any time and it would show the minimap. Hopefully that makes sense, if it does what you need it to, feel free to close the issue! =)

**Comment by nonnymoose** [comment]
Sorry for the late response. This works perfectly!

**Comment by ansballard** [comment]
Awesome, glad to hear it!
