### ISSUE TITLE
prevent autoclosing if mouse cursor over minimap 

### ISSUE THREAD

**Issue by nobodo** [ansballard/minimap-autohider#9]
Trying to click the cog wheel button was a bit frustrating when autohide kicked in just before mouse cursor was reaching the button.

**Comment by ansballard** [comment]
weird, I can't reproduce that on my box (windows 10). What OS are you using, and is atom/this package up to date? Thanks for the issue!

**Comment by ansballard** [comment]
Going to close this for my sanity, but if it isn't actually resolved just let me know!
